name: Android CI

# 1
on:
  # 2
  pull_request:
    types:
      - opened
    branches:
      - 'master'
  #  pull_request:
  #    branches: [ "master" ]

  # 3
  workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      # 10
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.10.0"
          channel: 'stable'
          cache: true

      - name: Create .env file
        run: |
          touch ${{ github.workspace }}/assets/.config_env
          echo START=${{ vars.START }} >> .config_env

          echo "cat .config_env"
          cat ${{ github.workspace }}/assets/.config_env
          
          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}/assets
      - name: Get dependencies
        run: flutter pub get
      - name: Test
        run:  flutter test test/widget_test.dart

      # Runs a set of commands using the runners shell
#      - name: Start release build
#        run: flutter build apk
